/**
 * Given a question and the documents a user's role is cleared to see, this
 * retrieves the most relevant documents and synthesizes a grounded answer.
 *
 * If ANTHROPIC_API_KEY is set, the answer is generated by an LLM that is
 * given ONLY the retrieved snippets (not the full document set) and told to
 * answer from them and cite which document each claim came from. If no key
 * is set, a local fallback simply surfaces the best-matching snippets
 * directly, so the feature is still fully usable and demoable.
 */

const { rankDocuments } = require("./retrieval");

const CLEARANCE_RANK = { public: 0, team: 1, founder: 2 };

// Below this similarity score, a "match" isn't actually relevant enough to
// answer from - it's just the least-bad option in a small document set.
const RELEVANCE_THRESHOLD = 0.12;

function clearanceAllowed(userRole, docClearance) {
  const userMax = userRole === "founder" ? 2 : userRole === "member" ? 1 : 0;
  return CLEARANCE_RANK[docClearance] <= userMax;
}

async function synthesizeWithLLM(question, matches) {
  const context = matches
    .map((m, i) => `[Doc ${i + 1}: "${m.doc.title}" | clearance: ${m.doc.clearance}]\n${m.doc.content}`)
    .join("\n\n");

  const prompt = `You are an internal knowledge assistant for a startup. Answer the
question using ONLY the documents below. If the documents don't contain a real
answer, say so plainly rather than guessing. Cite which document(s) you used
by their title in your answer.

Documents:
${context}

Question: ${question}

Give a concise, direct answer (3-5 sentences max).`;

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01"
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-6",
      max_tokens: 500,
      messages: [{ role: "user", content: prompt }]
    })
  });

  if (!response.ok) throw new Error(`LLM request failed with status ${response.status}`);

  const data = await response.json();
  const textBlock = (data.content || []).find((b) => b.type === "text");
  if (!textBlock) throw new Error("No text content returned by LLM.");
  return textBlock.text.trim();
}

function synthesizeLocally(matches) {
  if (!matches.length) {
    return "I couldn't find anything relevant to that question in the documents you're cleared to see. Either it hasn't been added to the knowledge base yet, or it exists in a document above your clearance level.";
  }
  const top = matches[0];
  return (
    `Best match from "${top.doc.title}": ${top.doc.content.slice(0, 300)}` +
    (top.doc.content.length > 300 ? "…" : "") +
    `\n\n(This is a direct excerpt — add an ANTHROPIC_API_KEY in .env to get a synthesized, cited answer instead of a raw snippet.)`
  );
}

/**
 * @param {string} question
 * @param {Array} allDocuments - all documents in the workspace
 * @param {string} userRole - "founder" | "member"
 * @returns {Promise<{answer: string, sources: Array}>}
 */
async function answerQuestion(question, allDocuments, userRole) {
  const visibleDocs = allDocuments.filter((d) => clearanceAllowed(userRole, d.clearance));

  const ranked = rankDocuments(question, visibleDocs);
  const matches = ranked.filter((r) => r.score >= RELEVANCE_THRESHOLD).slice(0, 3);

  let answer;
  if (matches.length && process.env.ANTHROPIC_API_KEY) {
    try {
      answer = await synthesizeWithLLM(question, matches);
    } catch (err) {
      console.warn("[knowledgeEngine] LLM synthesis failed, using local fallback:", err.message);
      answer = synthesizeLocally(matches);
    }
  } else {
    answer = synthesizeLocally(matches);
  }

  return {
    answer,
    sources: matches.map((m) => ({
      document: m.doc._id,
      title: m.doc.title,
      clearance: m.doc.clearance,
      score: Math.round(m.score * 1000) / 1000
    }))
  };
}

module.exports = { answerQuestion, clearanceAllowed };
